name: todo_app_crossplatform
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

assets:
  - .env
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
